name: Build and Deploy Identity API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Image
      run: |
        docker build -t bulletshopacr.azurecr.io/bulletshop-identity:latest .
        docker push bulletshopacr.azurecr.io/bulletshop-identity:latest

    - name: Restart Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: bulletshop-identity-api
        images: bulletshopacr.azurecr.io/bulletshop-identity:latest